language: python
dist: xenial

python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"

env:
  - DJANGO=2.1
  - DJANGO=2.2
  - DJANGO=3.0
  - DJANGO=3.1

install:
  - pip install tox tox-travis

script:
  - tox

after_success:
  - test $TOXENV = "py39-django31" && coveralls

deploy:
  provider: pypi
  user: thorgate
  password:
    secure: >
      ed+XJteAdeeS8DmnACV3UKSu/s/qMv6u6xPITGKQomkAhxuJFo3m8LRjm3lMnJI1NN8EIuYCiMjHPEEXXwqi8+uGwUzPNpqYwBjrK8v6TVUxY
      tNLIwTzhwRu+pt/V3BxnhyqTEwF0NAi+diIqeQVsVPl8lHrQRye+y4Sco33VKGtJi5+8qgdYnbh5xA5QeZmDSkT/n1mJE9C9p0O6Dlgco2kwC
      MI/YoCSM3y3jKH53ZMdYHf6FOWgMYoyaNjUEc2jGJyfp61X3+JQJhg8jxSFHNl06vzp+Eyei90RMMM/QccBSXUMSdAdXBXoDnmoQ7PGV8OUU5
      H4r9TCbwpP4UzyxboyE2MK9+XyyIPiP9Cj0z78oIBfYSINiOoEOwaSAgU8P49ok3Ba7oIKBWXeI13rgo2JSkWPTdhhHESmeVIeX30HoyY41u3
      eC3nPzsDIUdBzcgMK1bZ+4WgiEjsKpER7SPgpvxULBPHtaNZlnovRVD+QiYWnmxHbqnpLrgMCT3NRJsoWm9AZErHkRKzu3213kaDf1k7ivDad
      r7iZnEoDEj8Vjp1qQF0rnbu8/eFKh5XG/myNIihrfpy89A9Mp0mAuhaRweJyz3eGoio856o+3fF+bpUzi4qVN4vYRlryt+3nb0K5qamT60Zvk
      bP8SL3hRUQy0ifWFZW7q8tGSBcM+w=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: thorgate/tg-react
    python: "3.9"
    condition: "$DJANGO = 3.1"

notifications:
    email: false
