language: python
dist: xenial

python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"

env:
  - DJANGO=2.2
  - DJANGO=3.0
  - DJANGO=3.1
  global:
    secure: |
      B3ocZQIgc3y13jGgbCBPTqiToke1X9j3E5LBxRdicHbNBUO66RWy5+i6vNUwt8m+EEg738L1Or3Q//CHO3HuKRLtxz4jn
      I/nPa6ZhHE3eNDGz/Vp8FHmycOiN0BYT4h3wS4B2nLAh46PPMTdv7Jg8L4yy7qr15le72/LNsRYJVAxCi+ggk/Jf87d8T
      8Vqo31huKs7SoSjMcM8jELQsyfDuw1MC2EyPJhK47KjmzWO0G37wnesbMCIkLwLaSX0trkBySBlHdWdQJoKT4+1SiXK1g
      yMoeewLyUjeN7qV2UQQAJnBh0SFHYJPfTGH40boGueKkLLugjuJGFYbPHhWMGucZxLMLbsRQ9LfU69dAVVqyAeg+ooLh9
      vW05atH4wruAREbbzwCD4dAIty9sndfXXM885RxjxUdq8QcCVzv4t2d+xHPliCCu68y5qkU0iH8EbPz1VDu6OeGsC3Chf
      UxWPpgNv+6FDh4tNOXfIRTqeXrHXsUou4h2JeeBruc3Ky3zMaU4wO+6F4Iu32ryECHzsypAtmDke5cgBWXqR5EwZspyJl
      6tGytxkYeCMnQ9MW8M3GnAR4TiI/MKHT2VO5Pvb9IJRSaS6EsnXNJlH02IteXTe39LUGHwdkluO5cfjNj2ky6x7wNEpij
      KsqIALPPQDcDc1CFzunntYvU16gbSSzk=

install:
  - pip install tox tox-travis tox-poetry

script:
  - tox
  - poetry --help

after_success:
  - test $TOXENV = "py39-django31" && coveralls

deploy:
  provider: script
  script: poetry publish --username __token__ --password $PYPI_TOKEN --build
  on:
    tags: true
    repo: thorgate/tg-react
    python: "3.9"
    condition: "$DJANGO = 3.1"

notifications:
    email: false
